spring.application.name=GoGym

# Links para a documentação do Swagger
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

# Configurações da conexão com o banco
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/GoGym
spring.datasource.username=postgres
spring.datasource.password=postgres

# Configurações do Spring Security
api.security.token.secret=11a2b80e-f755-408b-b864-5423dd1ff0a2